name: ${PROJECT_NAME}

services:
  db:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}-db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./_entrypoint:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Bangkok
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app-net

  app:
    depends_on:
      db:
        condition: service_healthy
    image: pairrz/on-track:latest
    container_name: ${PROJECT_NAME}-app
    restart: always
    ports:
      - "${APP_PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${PROJECT_NAME}-db:5432/${POSTGRES_DB}
      NODE_ENV: production
      TZ: Asia/Bangkok
    post_start:
      - command: ["npx", "prisma", "migrate", "deploy"]
    volumes:
      - ./logs:/app/logs
    networks:
      - app-net

volumes:
  pg-data:

networks:
  app-net: